name: Linting, formatting and Build on PR

on:
    push:
        paths: [ "scan-guard/**" ]
    pull_request:
        branches: [ "dev" ]
        paths: [ "scan-guard/**" ]

jobs:
    Frontend-Continuous-Integreation:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./scan-guard

        steps:
        -   name: Checkout the Repository
            uses: actions/checkout@v3

        -   uses: actions/setup-node@v4
            with:
                node-version: 20

        -   name: Install dependencies
            run: npm install --legacy-peer-deps

        -   name: Run linting check
            run: npm run lint:check

        -   name: Run formatting check
            run: npm run format:check

        -   name: Build
            run: npm run build
    
    Backend-Continuous-Integreation:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./backend

        steps:
        -   name: Checkout the Repository
            uses: actions/checkout@v3

        -   uses: actions/setup-node@v4
            with:
                node-version: 20

        -   name: Install dependencies
            run: npm install --legacy-peer-deps

        -   name: Run linting check
            run: npm run lint:check

        -   name: Run formatting check
            run: npm run format:check

        -   name: Build
            run: npm run build